/*  DBZ / stuff / colors.inc  —  chat / UI colours  */
#if defined _dbz_colors_included
    #endinput
#endif
#define _dbz_colors_included

#define COLOR_RED           0xFF0000AA
#define COLOR_GREEN         0x33AA33AA
#define COLOR_YELLOW        0xFFFF00AA
#define COLOR_ORANGE        0xFF9900AA
#define COLOR_BLUE          0x1E90FFAA
#define COLOR_LIGHTBLUE     0x33CCFFAA
#define COLOR_WHITE         0xFFFFFFAA
#define COLOR_GREY          0xAFAFAFAA
#define COLOR_PINK          0xFF66FFAA
#define COLOR_ADMIN         0x24FF0AB9
